-- MySQL Script generated by MySQL Workbench
-- 12/07/16 12:41:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pardon_maman
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pardon_maman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pardon_maman` DEFAULT CHARACTER SET utf8 ;
USE `pardon_maman` ;

-- -----------------------------------------------------
-- Table `pardon_maman`.`Style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pardon_maman`.`Style` (
  `Id_style` INT NOT NULL AUTO_INCREMENT,
  `Font_color` VARCHAR(45) NOT NULL,
  `Background_color` VARCHAR(45) NOT NULL,
  `Font_style` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_style`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pardon_maman`.`Disclaimer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pardon_maman`.`Disclaimer` (
  `Id_disclaimer` INT NOT NULL AUTO_INCREMENT,
  `CGU` VARCHAR(255) NOT NULL,
  `CGV` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id_disclaimer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pardon_maman`.`Contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pardon_maman`.`Contest` (
  `Id_contest` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Start_date` DATE NOT NULL,
  `End_date` DATE NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Is_disabled` TINYINT(1) NULL,
  `Style_Id_style` INT NOT NULL,
  `Disclaimer_Id_disclaimer` INT NOT NULL,
  PRIMARY KEY (`Id_contest`),
  INDEX `fk_Contest_Style1_idx` (`Style_Id_style` ASC),
  INDEX `fk_Contest_Disclaimer1_idx` (`Disclaimer_Id_disclaimer` ASC),
  CONSTRAINT `fk_Contest_Style1`
    FOREIGN KEY (`Style_Id_style`)
    REFERENCES `pardon_maman`.`Style` (`Id_style`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contest_Disclaimer1`
    FOREIGN KEY (`Disclaimer_Id_disclaimer`)
    REFERENCES `pardon_maman`.`Disclaimer` (`Id_disclaimer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pardon_maman`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pardon_maman`.`User` (
  `id_user` INT NOT NULL,
  `Type` TINYINT(1) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Gender` VARCHAR(45) NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Telephone` INT(10) NULL,
  `City` VARCHAR(45) NULL,
  `Update_date` DATE NULL,
  `Signin_date` DATE NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pardon_maman`.`Participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pardon_maman`.`Participation` (
  `Id_Participation` INT NOT NULL AUTO_INCREMENT,
  `Contest_id_contest` INT NOT NULL,
  `Id_photo` INT NOT NULL,
  `Votes` VARCHAR(45) NULL,
  `User_id_user` INT NOT NULL,
  PRIMARY KEY (`Id_Participation`, `Contest_id_contest`, `User_id_user`),
  INDEX `fk_Participation_User1_idx` (`User_id_user` ASC),
  CONSTRAINT `fk_historique_Concour1`
    FOREIGN KEY (`Contest_id_contest`)
    REFERENCES `pardon_maman`.`Contest` (`Id_contest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participation_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `pardon_maman`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pardon_maman`.`User_has_Concour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pardon_maman`.`User_has_Concour` (
  `User_id_user` INT NOT NULL,
  `Concour_id_concour` INT NOT NULL,
  PRIMARY KEY (`User_id_user`, `Concour_id_concour`),
  INDEX `fk_User_has_Concour_Concour1_idx` (`Concour_id_concour` ASC),
  INDEX `fk_User_has_Concour_User1_idx` (`User_id_user` ASC),
  CONSTRAINT `fk_User_has_Concour_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `pardon_maman`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Concour_Concour1`
    FOREIGN KEY (`Concour_id_concour`)
    REFERENCES `pardon_maman`.`Contest` (`Id_contest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
